//
//  AppNamesPresenter.swift
//  observable-withUIElement
//
//  Created by khaled elsedek on 8/28/19.
//  Copyright (c) 2019 khaled elsedek. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
import RxCocoa
import RxSwift

protocol AppNamesPresenterInput {
    func getNameFromInterActor(name: String)
}

protocol AppNamesPresenterOutput: class {
    func givenameforlabel(name: String)
}

class AppNamesPresenter: AppNamesPresenterInput {
    
    
    
    weak var output: AppNamesPresenterOutput?
    
    // MARK: Presentation logic
    func getNameFromInterActor(name: String) {
        output?.givenameforlabel(name: name)
    }
}
