//
//  AppNamesModels.swift
//  observable-withUIElement
//
//  Created by khaled elsedek on 8/28/19.
//  Copyright (c) 2019 khaled elsedek. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct AppNamesScene {
    
}
