//
//  AppNamesInteractor.swift
//  observable-withUIElement
//
//  Created by khaled elsedek on 8/28/19.
//  Copyright (c) 2019 khaled elsedek. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
import RxSwift
import RxCocoa
protocol AppNamesInteractorInput {
    func getNameFromTxtField(nameEntry : String)
}

protocol AppNamesInteractorOutput {
    func getNameFromInterActor(name: String)
}

protocol AppNamesDataSource {
    
}

protocol AppNamesDataDestination {
    
}

class AppNamesInteractor: AppNamesInteractorInput, AppNamesDataSource, AppNamesDataDestination {
    
    
    
    
    var output: AppNamesInteractorOutput?
    let disposeBag = DisposeBag()
    // MARK: Business logic
    
    func getNameFromTxtField(nameEntry: String) {
        if nameEntry == "" {
            output?.getNameFromInterActor(name: "Type your name below.")
        } else {
            output?.getNameFromInterActor(name: "Hello, \(nameEntry)")
        }
    }
}
