//
//  AppNamesRouter.swift
//  observable-withUIElement
//
//  Created by khaled elsedek on 8/28/19.
//  Copyright (c) 2019 khaled elsedek. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol AppNamesRouterInput {
    
}

protocol AppNamesRouterDataSource: class {
    
}

protocol AppNamesRouterDataDestination: class {
    
}

class AppNamesRouter: AppNamesRouterInput {
    
    weak var viewController: AppNamesViewController!
    weak private var dataSource: AppNamesRouterDataSource!
    weak var dataDestination: AppNamesRouterDataDestination!
    
    init(viewController: AppNamesViewController, dataSource: AppNamesRouterDataSource, dataDestination: AppNamesRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
