//
//  AppNamesConfigurator.swift
//  observable-withUIElement
//
//  Created by khaled elsedek on 8/28/19.
//  Copyright (c) 2019 khaled elsedek. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension AppNamesInteractor: AppNamesViewControllerOutput, AppNamesRouterDataSource, AppNamesRouterDataDestination {
}

extension AppNamesPresenter: AppNamesInteractorOutput {
}

class AppNamesConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = AppNamesConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: AppNamesViewController) {
        
        let presenter = AppNamesPresenter()
        presenter.output = viewController
        
        let interactor = AppNamesInteractor()
        interactor.output = presenter
        
        let router = AppNamesRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
